### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by STARK-775178** [kwwcv/SelfMotion#1]
After a round of training, Testing reported an error.
Traceback (most recent call last):
  File "/home/stark/project/SelfMotion/train.py", line 184, in <module>
    main()
  File "/home/stark/project/SelfMotion/train.py", line 172, in main
    eval_motion_displacement(device=device, model=model,
  File "/home/stark/project/SelfMotion/test.py", line 87, in eval_motion_displacement
    curr_valid_pixel_map = valid_pixel_maps[:, s]
IndexError: index 7 is out of bounds for axis 1 with size 5

**Comment by STARK-775178** [comment]
There is also a question: why the train code copy the data when log?

**Comment by kwwcv** [comment]
Can you try to generate test data again using gen_data.py? There was a mistake at line 52. You can also follow motionnet to generate the test data.

**Comment by STARK-775178** [comment]
The training code is running. Thank you 8D

**Comment by ZuoYuFan-bee** [comment]
I want to ask why gen _ data.py can not find the corresponding bin file when processing, I downloaded the trainval dataset from Nuscenes, if you can ask the blogger to share the pre-trained model or dataset
